# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chan/qt/onvifdemo/onvifdemo/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_6.addWidget(self.comboBox_4)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_7.addWidget(self.comboBox_5)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_8.addWidget(self.comboBox_6)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_9.addWidget(self.comboBox_7)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout_10.addWidget(self.comboBox_8)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_boradcast = QtWidgets.QPushButton(self.tab)
        self.pushButton_boradcast.setObjectName("pushButton_boradcast")
        self.horizontalLayout_11.addWidget(self.pushButton_boradcast)
        self.pushButton_Probe = QtWidgets.QPushButton(self.tab)
        self.pushButton_Probe.setObjectName("pushButton_Probe")
        self.horizontalLayout_11.addWidget(self.pushButton_Probe)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.pushButton_GetDeviceInformation = QtWidgets.QPushButton(self.tab)
        self.pushButton_GetDeviceInformation.setObjectName("pushButton_GetDeviceInformation")
        self.horizontalLayout_12.addWidget(self.pushButton_GetDeviceInformation)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_14.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_14.addWidget(self.pushButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_15.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_15.addWidget(self.pushButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_13.addWidget(self.checkBox)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_13.addWidget(self.dateTimeEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_17.addWidget(self.pushButton_9)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_18.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_19.addWidget(self.comboBox_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_20.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_21.addWidget(self.lineEdit_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_23.addWidget(self.lineEdit_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_22.addWidget(self.lineEdit_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_24.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_24.addWidget(self.pushButton_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_26.addWidget(self.label_18)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_26.addWidget(self.comboBox_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_25.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_25.addWidget(self.pushButton_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_27.addWidget(self.lineEdit_8)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_27.addWidget(self.horizontalSlider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_28.addWidget(self.label_20)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_28.addWidget(self.lineEdit_9)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_28.addWidget(self.horizontalSlider_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_29.addWidget(self.label_21)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_29.addWidget(self.lineEdit_10)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_29.addWidget(self.horizontalSlider_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_30.addWidget(self.label_22)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_30.addWidget(self.lineEdit_11)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_30.addWidget(self.horizontalSlider_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.listView = QtWidgets.QListView(self.groupBox_4)
        self.listView.setObjectName("listView")
        self.verticalLayout_11.addWidget(self.listView)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_11.addWidget(self.lineEdit_12)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButton_GetPresets = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_GetPresets.setObjectName("pushButton_GetPresets")
        self.horizontalLayout_31.addWidget(self.pushButton_GetPresets)
        self.pushButton_SetPreset = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_SetPreset.setObjectName("pushButton_SetPreset")
        self.horizontalLayout_31.addWidget(self.pushButton_SetPreset)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_32.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_32.addWidget(self.pushButton_20)
        self.verticalLayout_11.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_33.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_33.addWidget(self.pushButton_22)
        self.verticalLayout_11.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton_GeoMove = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_GeoMove.setObjectName("pushButton_GeoMove")
        self.horizontalLayout_34.addWidget(self.pushButton_GeoMove)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_34.addWidget(self.pushButton_24)
        self.verticalLayout_11.addLayout(self.horizontalLayout_34)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_15.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.radioButton_Continuous = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_Continuous.setObjectName("radioButton_Continuous")
        self.horizontalLayout_35.addWidget(self.radioButton_Continuous)
        self.radioButton_Relative = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_Relative.setObjectName("radioButton_Relative")
        self.horizontalLayout_35.addWidget(self.radioButton_Relative)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_35.addWidget(self.radioButton_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_11.setObjectName("comboBox_11")
        self.horizontalLayout_36.addWidget(self.comboBox_11)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_12.setObjectName("comboBox_12")
        self.horizontalLayout_36.addWidget(self.comboBox_12)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_13.setObjectName("comboBox_13")
        self.horizontalLayout_36.addWidget(self.comboBox_13)
        self.verticalLayout_13.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_leftup = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_leftup.setObjectName("pushButton_leftup")
        self.horizontalLayout_37.addWidget(self.pushButton_leftup)
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_up.setObjectName("pushButton_up")
        self.horizontalLayout_37.addWidget(self.pushButton_up)
        self.pushButton_rightup = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_rightup.setObjectName("pushButton_rightup")
        self.horizontalLayout_37.addWidget(self.pushButton_rightup)
        self.verticalLayout_13.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.pushButton_left = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_left.setObjectName("pushButton_left")
        self.horizontalLayout_38.addWidget(self.pushButton_left)
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_38.addWidget(self.pushButton_reset)
        self.pushButton_right = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_right.setObjectName("pushButton_right")
        self.horizontalLayout_38.addWidget(self.pushButton_right)
        self.verticalLayout_13.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.pushButton_leftdown = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_leftdown.setObjectName("pushButton_leftdown")
        self.horizontalLayout_39.addWidget(self.pushButton_leftdown)
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_down.setObjectName("pushButton_down")
        self.horizontalLayout_39.addWidget(self.pushButton_down)
        self.pushButton_rightdown = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_rightdown.setObjectName("pushButton_rightdown")
        self.horizontalLayout_39.addWidget(self.pushButton_rightdown)
        self.verticalLayout_13.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.pushButton_zoomout = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_zoomout.setObjectName("pushButton_zoomout")
        self.horizontalLayout_40.addWidget(self.pushButton_zoomout)
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout_40.addWidget(self.pushButton_Stop)
        self.pushButton_zoomin = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_zoomin.setObjectName("pushButton_zoomin")
        self.horizontalLayout_40.addWidget(self.pushButton_zoomin)
        self.verticalLayout_13.addLayout(self.horizontalLayout_40)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_15.addWidget(self.groupBox_5)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_41.addWidget(self.tabWidget)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_17.addWidget(self.label_23)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_17.addWidget(self.textBrowser_2)
        self.horizontalLayout_41.addLayout(self.verticalLayout_17)
        self.horizontalLayout_41.setStretch(0, 2)
        self.horizontalLayout_41.setStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户姓名"))
        self.label_2.setText(_translate("MainWindow", "用户密码"))
        self.label_3.setText(_translate("MainWindow", "选择网卡"))
        self.label_4.setText(_translate("MainWindow", "指定设备"))
        self.label_5.setText(_translate("MainWindow", "过滤设备"))
        self.label_6.setText(_translate("MainWindow", "搜索间隔"))
        self.label_7.setText(_translate("MainWindow", "超时时间"))
        self.label_8.setText(_translate("MainWindow", "搜索策略"))
        self.label_9.setText(_translate("MainWindow", "设备列表"))
        self.label_10.setText(_translate("MainWindow", "配置文件"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_boradcast.setText(_translate("MainWindow", "广播搜索"))
        self.pushButton_Probe.setText(_translate("MainWindow", "单播搜索"))
        self.pushButton_3.setText(_translate("MainWindow", "一键获取"))
        self.pushButton_GetDeviceInformation.setText(_translate("MainWindow", "设备信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "搜索"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_GetPresets.setText(_translate("MainWindow", "获取预置位"))
        self.pushButton_SetPreset.setText(_translate("MainWindow", "添加预置位"))
        self.pushButton_19.setText(_translate("MainWindow", "当前预置位"))
        self.pushButton_20.setText(_translate("MainWindow", "当前坐标值"))
        self.pushButton_21.setText(_translate("MainWindow", "调用起始位"))
        self.pushButton_22.setText(_translate("MainWindow", "设置起始位"))
        self.pushButton_GeoMove.setText(_translate("MainWindow", "开始巡航"))
        self.pushButton_24.setText(_translate("MainWindow", "停止巡航"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton_Continuous.setText(_translate("MainWindow", "绝对"))
        self.radioButton_Relative.setText(_translate("MainWindow", "相对"))
        self.radioButton_3.setText(_translate("MainWindow", "连续"))
        self.pushButton_leftup.setText(_translate("MainWindow", "↖"))
        self.pushButton_up.setText(_translate("MainWindow", "↑"))
        self.pushButton_rightup.setText(_translate("MainWindow", "↗"))
        self.pushButton_left.setText(_translate("MainWindow", "←"))
        self.pushButton_reset.setText(_translate("MainWindow", "复位"))
        self.pushButton_right.setText(_translate("MainWindow", "→"))
        self.pushButton_leftdown.setText(_translate("MainWindow", "↙"))
        self.pushButton_down.setText(_translate("MainWindow", "↓"))
        self.pushButton_rightdown.setText(_translate("MainWindow", "↘"))
        self.pushButton_zoomout.setText(_translate("MainWindow", "+"))
        self.pushButton_Stop.setText(_translate("MainWindow", "停止"))
        self.pushButton_zoomin.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "云台"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "tab_4"))
        self.label_23.setText(_translate("MainWindow", "日志"))

